openapi: 3.0.1
info:
  title: demo-secrets
  description: API Definition of demo-secrets
  version: 1.0.0
servers:
- url: http://localhost:8290/secrets
paths:
  /:
    get:
      responses:
        default:
          description: Default response
