ARG CNXT_DOCKER_ENDPOINT

FROM $CNXT_DOCKER_ENDPOINT/default/wso2-mi-alpine:1.1.0

#RUN rm -rf /home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/carbonapps/helloworld_1.0.0.car

COPY secrets_1.0.0.car /home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/carbonapps/
